In [1]:
from dados_api import previsao_temperatura

In [ ]:
df1,df2 = previsao_temperatura(-23.40899837804558, -46.90081462618057)

Coordinates: -23.37434196472168°N -46.8907470703125°E
Elevation: 739.0 m asl
Timezone difference to GMT+0: 0s

Hourly data
                          date  temperature_2m
0   2026-10-21 00:00:00+00:00       13.850000
1   2026-10-21 01:00:00+00:00       13.300000
2   2026-10-21 02:00:00+00:00       12.800000
3   2026-10-21 03:00:00+00:00       12.650000
4   2026-10-21 04:00:00+00:00       12.900000
..                        ...             ...
163 2026-10-27 19:00:00+00:00       17.799999
164 2026-10-27 20:00:00+00:00       17.400000
165 2026-10-27 21:00:00+00:00       16.950001
166 2026-10-27 22:00:00+00:00       16.500000
167 2026-10-27 23:00:00+00:00       16.100000

[168 rows x 2 columns]

In [3]:
df1

                         date  temperature_2m  dia  mes    dia_semana
0   2026-10-21 00:00:00+00:00       13.850000   21   10  Quarta-feira
1   2026-10-21 01:00:00+00:00       13.300000   21   10  Quarta-feira
2   2026-10-21 02:00:00+00:00       12.800000   21   10  Quarta-feira
3   2026-10-21 03:00:00+00:00       12.650000   21   10  Quarta-feira
4   2026-10-21 04:00:00+00:00       12.900000   21   10  Quarta-feira
..                        ...             ...  ...  ...           ...
163 2026-10-27 19:00:00+00:00       17.799999   27   10   Terça-feira
164 2026-10-27 20:00:00+00:00       17.400000   27   10   Terça-feira
165 2026-10-27 21:00:00+00:00       16.950001   27   10   Terça-feira
166 2026-10-27 22:00:00+00:00       16.500000   27   10   Terça-feira
167 2026-10-27 23:00:00+00:00       16.100000   27   10   Terça-feira

[168 rows x 5 columns]

In [4]:
df2

   dia  mes     dia_semana  temperatura_media
0   21   10   Quarta-feira          17.558332
1   22   10   Quinta-feira          19.037500
2   23   10    Sexta-feira          18.754168
3   24   10         Sábado          21.245832
4   25   10        Domingo          19.535418
5   26   10  Segunda-feira          18.404167
6   27   10    Terça-feira          16.185417